name: Reusable Plan and Apply

on: 
    workflow_call:
        secrets:
            TF_vars:
                required: false


permissions:
    id-token: write
    contents: read

jobs:
  run-tf:
    runs-on: ubuntu-latest

    steps: 

    - uses: actions/checkout@v4

    - run: |
        echo "tf_vars"
        echo $TF_vars
        echo "secrets"
        echo ${{ secrets.TF_vars }}

    - run: |
        for i in $TF_vars; do
            echo $i
            # i=$(echo $i | sed 's/=.*//g')=$(echo ${i#*=} | base64 -di | base64 -di)
            # echo ::add-mask::${i#*=}
            # printf '%s\n' "$i" >> $GITHUB_ENV
          done
    

    - name: 'Plan Run'
      run: |
        terraform init
        # terraform plan -input=false -var-file=./secrets.tfvars
        terraform plan -input=false 
      working-directory: terraform

    # - name: 'Apply Run'
    #   run: |
    #     terraform apply -auto-approve -input=false -var-file=./secrets.tfvars
    #   working-directory: terraform
